# Amazon Web Scraper Project

In [16]:
# import libraries

from bs4 import BeautifulSoup
import requests
import time
import datetime

import smtplib

In [46]:


URL = 'https://www.amazon.in/DUDEME-Programmer-Coding-Developer-T-Shirt/dp/B0C2HF6H4J/ref=sr_1_5?sr=8-5'

headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}

page = requests.get(URL, headers=headers)

soup1 = BeautifulSoup(page.content, "html.parser")

soup2 = BeautifulSoup(soup1.prettify(), "html.parser")

title = soup2.find(id='productTitle').get_text().strip()

price = soup2.find(class_="a-price aok-align-center reinventPricePriceToPayMargin priceToPay apex-pricetopay-value").get_text(strip=True)[1:]

# print(soup2)
print(title)
print(price)

DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Cotton T-Shirts for Programmer, Coding, Developer, Software Mens, Round Neck T Shirts for Women, Half Sleeve Tshirt for Men
499

In [50]:
import datetime

today = datetime.date.today()

print(today)

2026-06-11

In [52]:
import csv

header = ['Title', 'Price', 'Date']
data = [title, price, today]

#with open('AmazonWebScraperDataset.csv', 'w', newline='', encoding='UTF8') as f:
    #writer = csv.writer(f)
    #writer.writerow(header)
    #writer.writerow(data)

In [64]:
import pandas as pd 

df = pd.read_csv(r"C:\Users\Khooni Darinda\Downloads\Alex Python\Amazon Web Scraping  Project\AmazonWebScraperDataset.csv")

df

                                               Title  Price        Date
0  DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
1  DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
2  DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
3  DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
4  DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11

In [63]:
# Now we are appending data to the csv

with open('AmazonWebScraperDataset.csv', 'a+', newline='', encoding='UTF8') as f:
    writer = csv.writer(f)
    writer.writerow(data)

In [ ]:
def check_price():
    URL = 'https://www.amazon.in/DUDEME-Programmer-Coding-Developer-T-Shirt/dp/B0C2HF6H4J/ref=sr_1_5?sr=8-5'

    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36", "Accept-Encoding":"gzip, deflate", "Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8", "DNT":"1","Connection":"close", "Upgrade-Insecure-Requests":"1"}

    page = requests.get(URL, headers=headers)

    soup1 = BeautifulSoup(page.content, "html.parser")

    soup2 = BeautifulSoup(soup1.prettify(), "html.parser")

    title = soup2.find(id='productTitle').get_text().strip()

    price = soup2.find(class_="a-price aok-align-center reinventPricePriceToPayMargin priceToPay apex-pricetopay-value").get_text(strip=True)[1:]

    import datetime

    today = datetime.date.today()

    print(today)

    with open('AmazonWebScraperDataset.csv', 'a+', newline='', encoding='UTF8') as f:
        writer = csv.writer(f)
        writer.writerow(data)

    if (price < 400):
        send_mail()

In [ ]:
while(True):
    check_price()
    time.sleep(86400)

2026-06-11

In [66]:
import pandas as pd 

df = pd.read_csv(r"C:\Users\Khooni Darinda\Downloads\Alex Python\Amazon Web Scraping  Project\AmazonWebScraperDataset.csv")

df

                                                Title  Price        Date
0   DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
1   DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
2   DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
3   DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
4   DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
5   DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
6   DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
7   DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
8   DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
9   DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
10  DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
11  DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
12  DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11
13  DUDEME in My World 1 + 1 = 10 T-Shirt, 100% Co...    499  2026-06-11

In [ ]:


def send_mail():
    server = smtplib.SMTP_SSL('smtp.gmail.com',465)
    server.ehlo()
    server.starttls()
    server.ehlo()
    server.login('abhinandankhajuria0@gmail.com','Khajuria$7172')
    
    subject = "The Shirt you want is below rs.400! Now is your chance to buy!"
    body = "Abhi, This is the moment we have been waiting for. Now is your chance to pick up the shirt of your dreams. Don't mess it up! Link here: https://www.amazon.in/DUDEME-Programmer-Coding-Developer-T-Shirt/dp/B0C2HF6H4J/ref=sr_1_5?sr=8-5"
   
    msg = f"Subject: {subject}\n\n{body}"
    
    server.sendmail(
        'abhinandankhajuria0@gmail.com',
        msg
     
    )